/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ── Warm Watercolor Palette ── */
        "paper-cream":   "#FBF3E7",
        "paper-warm":    "#F5EDE0",
        "paper-torn":    "#EEE2CE",
        "wc-peach":      "#F7B48A",
        "wc-coral":      "#F26D5B",
        "wc-rose":       "#E85A7C",
        "wc-terracotta": "#C74A3F",
        "wc-amber":      "#F2A03D",
        "wc-dusty-rose": "#D89A94",
        "wc-plum":       "#7A4A6B",
        "ink-warm":      "#4A3428",
        "ink-soft":      "#7A5C4E",
        "ink-meta":      "#B0857A",

        /* ── Legacy aliases (keep for any existing Tailwind references) ── */
        "on-tertiary":              "#ffffff",
        "on-error":                 "#ffffff",
        "surface-bright":           "#FBF3E7",
        "secondary":                "#C74A3F",
        "surface-variant":          "#EEE2CE",
        "surface-container":        "#F5EDE0",
        "background":               "#FBF3E7",
        "surface":                  "#FBF3E7",
        "outline":                  "#B0857A",
        "outline-variant":          "#EEE2CE",
        "error":                    "#ba1a1a",
        "error-container":          "#ffdad6",
        "on-error-container":       "#93000a",
        "on-surface":               "#4A3428",
        "on-surface-variant":       "#7A5C4E",
        "on-background":            "#4A3428",
        "primary":                  "#C74A3F",
        "on-primary":               "#ffffff",
        "primary-container":        "#F5EDE0",
        "on-primary-container":     "#C74A3F",
        "primary-fixed":            "#F7B48A",
        "primary-fixed-dim":        "#F26D5B",
        "inverse-primary":          "#F7B48A",
        "surface-container-low":    "#FBF3E7",
        "surface-container-high":   "#EEE2CE",
        "surface-container-highest":"#EEE2CE",
        "surface-container-lowest": "#ffffff",
        "surface-dim":              "#EEE2CE",
        "surface-tint":             "#C74A3F",
        "inverse-surface":          "#4A3428",
        "inverse-on-surface":       "#FBF3E7",
        "tertiary":                 "#7A4A6B",
        "on-tertiary-fixed":        "#4A3428",
        "tertiary-container":       "#FAEAF0",
        "on-tertiary-container":    "#7A4A6B",
        "tertiary-fixed":           "#FAEAF0",
        "tertiary-fixed-dim":       "#D89A94",
        "on-tertiary-fixed-variant":"#7A4A6B",
        "secondary-fixed":          "#F7B48A",
        "secondary-fixed-dim":      "#F2A03D",
        "on-secondary":             "#ffffff",
        "on-secondary-container":   "#C74A3F",
        "on-secondary-fixed":       "#4A3428",
        "on-secondary-fixed-variant":"#7A5C4E",
        "secondary-container":      "#F5EDE0",
        "on-primary-fixed":         "#4A3428",
        "on-primary-fixed-variant": "#7A5C4E",
      },
      fontFamily: {
        "headline": ["Playfair Display", "Georgia", "serif"],
        "body":     ["Lora", "Georgia", "serif"],
        "label":    ["DM Mono", "monospace"],
        "serif":    ["Source Serif 4", "Georgia", "serif"],
        "hand":     ["Caveat", "cursive"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg":      "0.5rem",
        "xl":      "0.75rem",
        "2xl":     "1rem",
        "full":    "9999px",
      },
    },
  },
  plugins: [],
}
