/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#f9f9f7",
        "secondary": "#516600",
        "tertiary-container": "#212f19",
        "surface-variant": "#e2e3e1",
        "surface-container": "#eeeeec",
        "primary-container": "#19301e",
        "on-primary-fixed": "#09200f",
        "inverse-surface": "#2f3130",
        "on-secondary-fixed": "#171e00",
        "on-primary-fixed-variant": "#344c38",
        "surface-container-low": "#f4f4f2",
        "outline": "#737972",
        "tertiary-fixed-dim": "#bbccac",
        "tertiary": "#0d1a06",
        "on-secondary-container": "#576c04",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-primary": "#b2ceb3",
        "secondary-fixed-dim": "#b7d165",
        "inverse-on-surface": "#f1f1ef",
        "tertiary-fixed": "#d7e8c7",
        "outline-variant": "#c3c8c0",
        "on-tertiary-fixed": "#121f0a",
        "on-primary": "#ffffff",
        "surface-tint": "#4c644f",
        "secondary-fixed": "#d3ee7e",
        "on-surface-variant": "#434842",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1b",
        "background": "#f9f9f7",
        "on-tertiary-container": "#87977a",
        "on-secondary-fixed-variant": "#3d4d00",
        "on-secondary": "#ffffff",
        "secondary-container": "#d3ee7e",
        "surface-dim": "#dadad8",
        "surface-container-highest": "#e2e3e1",
        "surface": "#f9f9f7",
        "primary-fixed-dim": "#b2ceb3",
        "surface-container-high": "#e8e8e6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#3c4b33",
        "on-primary-container": "#7f9981",
        "on-surface": "#1a1c1b",
        "primary": "#041b0b",
        "primary-fixed": "#ceeacf"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
